#Primeira tela pós login
san_sis_core_dw:
    path:     /
    defaults: { _controller: SanSISCoreDwBundle:Dw:index }

#JSON Carregamento dos combos
san_sis_core_dw_combos:
    path:     /{routeParam}/combos
    defaults: { _controller: SanSISCoreDwBundle:Dw:getComboData }

#Primeiro nível de dw
san_sis_core_dw_entry:
    path:     /{routeParam}
    defaults: { _controller: SanSISCoreDwBundle:Dw:routeParam }

#Exportação Primeiro nível de dw
san_sis_core_dw_entry_export:
    path:     /{routeParam}/export
    defaults: { _controller: SanSISCoreDwBundle:Dw:exportGridToExcel }

# JSON Pesquisa de nível 1
san_sis_core_dw_search:
    path:     /{routeParam}/search
    defaults: { _controller: SanSISCoreDwBundle:Dw:getGridData }

#Drill de n níveis
san_sis_core_dw_drill:
    path:     /{routeParam}/drill/{nivel}
    defaults: { _controller: SanSISCoreDwBundle:Dw:drill }

#Exportação Primeiro nível de dw
san_sis_core_dw_drill_export:
    path:     /{routeParam}/drill/{nivel}/export/
    defaults: { _controller: SanSISCoreDwBundle:Dw:exportDrillGridToExcel }

# JSON pesquisa de nível n
san_sis_core_dw_drill_search:
    path:     /{routeParam}/drill/{nivel}/data
    defaults: { _controller: SanSISCoreDwBundle:Dw:getDrillGridData }

#View
san_sis_core_dw_view:
    path:     /{routeParam}/view/{nivel}
    defaults: { _controller: SanSISCoreDwBundle:Dw:viewView }